name: ExplorerAgent
options:
  minimumXcodeGenVersion: 2.41.0
  xcodeVersion: "15.4"
targets:
  ExplorerAgent:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: App/Sources
      - path: App/Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yourcompany.exploreragent
        INFOPLIST_FILE: Info.plist
        SWIFT_VERSION: 5.9
    scheme:
      testTargets: [ExplorerAgentTests]
  ExplorerAgentTests:
    type: bundle.unit-test
    platform: iOS
    sources: [App/Tests]
    settings:
      base:
        TEST_HOST: ""
