name: iOS CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Cache derived data
        uses: actions/cache@v4
        with:
          path: ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-derived-data-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-derived-data-

      - name: Build and test
        run: |
          xcodebuild \
            -scheme ChatAI \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' \
            clean test
