name: iOS CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install XcodeGen
        run: brew install xcodegen

      - name: Tool versions
        run: |
          sw_vers
          xcodebuild -version
          xcodegen --version

      - name: Generate Xcode project
        run: xcodegen generate

      - name: Build
        run: |
          xcodebuild -project ExplorerAgent.xcodeproj \
            -scheme ExplorerAgent \
            -configuration Debug \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            build
