name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Install XcodeGen
        run: brew install xcodegen
      - name: Generate Xcode project
        run: xcodegen generate
      - name: Build (Simulator)
        run: xcodebuild -project WebhookChat.xcodeproj -scheme WebhookChat -destination 'platform=iOS Simulator,name=iPhone 15' build
